name: annahomestay
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
firebase_core: 2.24.2
  # Add other Firebase dependencies as needed, e.g., firebase_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

assets:
  - resources/anna-homestay.jpeg
  - resources/homestay1.jpg
  - resources/homestay2.jpg
  - resources/homestay3.jpg
  - resources/homestay4.jpg
  - resources/homestay5.jpg
  - resources/icon.png
  - splash.png
