name: annahomestay
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  image_picker: ^1.0.5
  # Add other Firebase dependencies as needed, e.g., firebase_auth

dev_dependencies:
  flutter_test:
    sdk: flutter
  get: ^4.6.6
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

assets:
  - resources/anna-homestay.jpeg
  - resources/homestay1.jpg
  - resources/homestay2.jpg
  - resources/homestay3.jpg
  - resources/homestay4.jpg
  - resources/homestay5.jpg
  - resources/icon.png
  - splash.png
