// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJd8beOBOV1U5Dnx-S3XwooYVOxY9KSe4',
    appId: '1:425277120843:web:6d9cbdcc261924acd608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    authDomain: 'annahomestay-ea338.firebaseapp.com',
    storageBucket: 'annahomestay-ea338.appspot.com',
    measurementId: 'G-YB7B4RKVZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh2ZTakhcdRWIWYxTZjTa4-u1y6c754Wc',
    appId: '1:425277120843:android:421e70914eeb843bd608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    storageBucket: 'annahomestay-ea338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzKTnCKVLXPteRItM4zf-pb9yLuxZTX-g',
    appId: '1:425277120843:ios:ace4f440f766aa1dd608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    storageBucket: 'annahomestay-ea338.appspot.com',
    iosBundleId: 'com.example.annahomestay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzKTnCKVLXPteRItM4zf-pb9yLuxZTX-g',
    appId: '1:425277120843:ios:9ca604b33d56fc64d608ce',
    messagingSenderId: '425277120843',
    projectId: 'annahomestay-ea338',
    storageBucket: 'annahomestay-ea338.appspot.com',
    iosBundleId: 'com.example.annahomestay.RunnerTests',
  );
}
